export const FETCH_PLAYERS_START = 'FETCH_PLAYERS_START';
export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
export const FETCH_PLAYERS_FAIL = 'FETCH_PLAYERS_FAIL';

export const FETCH_FAVORITE_PLAYER_SUCCESS = 'FETCH_FAVORITE_PLAYER_SUCCESS';
export const FETCH_FAVORITE_PLAYER_FAIL = 'FETCH_FAVORITE_PLAYER_FAIL';
export const FETCH_FAVORITE_PLAYER_START = 'FETCH_FAVORITE_PLAYER_START';

export const ADD_FAVORITE_PLAYER_SUCCESS = 'ADD_FAVORITE_PLAYER_SUCCESS';
export const ADD_FAVORITE_PLAYER_FAIL = 'ADD_FAVORITE_PLAYER_FAIL';
export const ADD_FAVORITE_PLAYER_START = 'ADD_FAVORITE_PLAYER_START';

export const DELETE_FAVORITE_PLAYER_SUCCESS = 'DELETE_FAVORITE_PLAYER_SUCCESS';
export const DELETE_FAVORITE_PLAYER_FAIL = 'DELETE_FAVORITE_PLAYER_FAIL';
export const DELETE_FAVORITE_PLAYER_START = 'DELETE_FAVORITE_PLAYER_START';

export const REGISTER_PLAYER_SUCCESS = 'REGISTER_PLAYER_SUCCESS';
export const REGISTER_PLAYER_FAIL = 'REGISTER_PLAYER_FAIL';
export const REGISTER_PLAYER_START = 'REGISTER_PLAYER_START';

export const EDIT_PLAYER_SUCCESS = 'EDIT_PLAYER_SUCCESS';
export const EDIT_PLAYER_FAIL = 'EDIT_PLAYER_FAIL';
export const EDIT_PLAYER_START = 'EDIT_PLAYER_START';

export const DELETE_PLAYER_SUCCESS = 'DELETE_PLAYER_SUCCESS';
export const DELETE_PLAYER_FAIL = 'DELETE_PLAYER_FAIL';
export const DELETE_PLAYER_START = 'DELETE_PLAYER_START';

export const ADD_MORE_INFO_PLAYER = 'ADD_MORE_INFO_PLAYER';
export const EDIT_PLAYER = 'EDIT_PLAYER';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
